services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_ORDER_SERVICE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    ports:
      - "8083:8080"
